version: "3.8"

x-redis: &redis
  image: redis:6.2.6    
  expose: ["6379"]
  command: ["redis-server"]

services:
  postgres:
    image: postgres:13
    container_name: auth_postgres
    expose:
      - '5432'
    env_file:
      - ./.env
      
  bucket:
    <<: *redis
    container_name: auth_bucket    

  redis:
    <<: *redis    
    container_name: auth_redis    

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    expose:
      - "6831"

  main:
    init: true
    container_name: auth_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT_APP=5000
      - WORKERS=1
    env_file:
      - ./.env
    expose:
      - "5000"
    depends_on:
      - postgres
      - redis

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile-nginx
    container_name: auth_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d 
    depends_on:
      - main
